/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import javafx.application.Application
import javafx.scene.Scene
import javafx.scene.control.Button
import javafx.scene.control.Label
import javafx.scene.layout.VBox
import javafx.stage.Stage

class MiVentana : Application() {
    override fun start(primaryStage: Stage) {
        // Crear el título como etiqueta
        val titulo = Label("Hola, esta es mi ventana con JavaFX en Kotlin")

        // Crear el botón
        val boton = Button("Haz clic aquí")
        boton.setOnAction {
            titulo.text = "¡Has hecho clic en el botón!"
        }

        // Organizar los elementos en un VBox (vertical)
        val layout = VBox(20.0) // espacio de 20 píxeles entre elementos
        layout.children.addAll(titulo, boton)

        // Crear la escena
        val scene = Scene(layout, 400.0, 200.0)

        // Configurar la ventana
        primaryStage.title = "Ejemplo Kotlin + JavaFX"
        primaryStage.scene = scene
        primaryStage.show()
    }
}

// Solo el main fuera de la clase
fun main() {
    Application.launch(MiVentana::class.java)
}

