/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    kotlin("jvm") version "1.9.23"
    application
}

repositories {
    mavenCentral()
}

dependencies {
    // JavaFX para Linux
    implementation("org.openjfx:javafx-controls:21.0.2:linux")
    implementation("org.openjfx:javafx-graphics:21.0.2:linux")
    implementation("org.openjfx:javafx-base:21.0.2:linux")

    // Si llegas a usar FXML, agrega:
    // implementation("org.openjfx:javafx-fxml:21.0.2:linux")
}

application {
    mainClass.set("org.example.AppKt") // Ajusta al paquete/clase donde tengas el main()
}

kotlin {
    jvmToolchain(21) // o la versión de tu JDK (17, 21…)
}
